### PR TITLE
First pull request

### PR DESCRIPTION
**Pull request by SajjadAhmad14**
In this project, we built a clone webpage of the NY Times page. We had to create a full article web page with buttons, navbar, content, and footer using flexbox, grid, and floats.

### CODE REVIEW

**Review by lucasmazo32 — COMMENTED** [review]
### Friendly reminder :memo:

Before submitting a code review, make sure to add a descriptive pull request. You can check an example [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/).

Kindly enable your stickler for this repo.

Please submit for a new review once they are ready!

For the moment this code review will be marked as invalid.

### Happy coding! :computer:

## Lucas Mazo

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, you have done quite well with this project :+1: Great work, however, there are a few changes we need to implement, kindly address the comments below: :smile: 

- Kindly implement the sticky feature for the footer as we applied to the nav
fn
- Kindly add instructions on how to clone the project in the README file
- Kindly add links to the ```More in space```, ```Editors pick``` section and ```Most popular```

Kindly implement these changes and submit another code review
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by eliasecasta** [comment]
We fixed Addo requested required changes.

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/SajjadAhmad14/New-York-Times-Website-Copy/development/index.html) shows good understanding and usage of the positioning and floating elements. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @SajjadAhmad14  & @e71az! :+1:
- You can now merge to master. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
